version: "2"
services:
  demo:
    build: .
    ports:
      - "8000:8000"
    environment:
      - JAEGER_SERVICE_NAME=hello_service
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_AGENT_PORT=6831
      - JAEGER_REPORTER_LOG_SPANS=true
      - JAEGER_SAMPLER_TYPE=const
      - JAEGER_SAMPLER_PARAM=1

  jaeger:
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
    image: "jaegertracing/all-in-one:1.6"
